apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cronjob-operator.fullname" . }}-manager-role
  labels:
  {{- include "cronjob-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cronjob-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cronjob-kubebuilder
    app.kubernetes.io/part-of: cronjob-kubebuilder
  {{- include "cronjob-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cronjob-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cronjob-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'