apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cronjob-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cronjob-kubebuilder
    app.kubernetes.io/part-of: cronjob-kubebuilder
  {{- include "cronjob-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}